var topologyData = {
  "nodes": [
    {"id": 1, "label": 'Node'},
    {"id": 2, "label": 'Node'},
    {"id": 3, "label": 'Node'},
    {"id": 4, "label": 'Node'},
    {"id": 5, "label": 'Node'},
    {"id": 6, "label": 'Node'},
    {"id": 7, "label": 'Node'},
    {"id": 8, "label": 'Node'},
    {"id": 9, "label": 'Node'},
    {"id": 10, "label": 'Node'},
  ],
  "edges": [
    {"from": 1, "to": 2},
    {"from": 2, "to": 3},
    {"from": 2, "to": 4},
    {"from": 2, "to": 5},
    {"from": 5, "to": 6},
    {"from": 5, "to": 7},
    {"from": 6, "to": 8},
    {"from": 1, "to": 8},
    {"from": 4, "to": 6},
    {"from": 7, "to": 2},
    {"from": 9, "to": 3},
    {"from": 10, "to": 9},
    {"from": 10, "to": 4},
  ],
};
