var topologyData = {
  "nodes": [
    {"id": 1, "label": 'Node'},
    {"id": 2, "label": 'Node'},
    {"id": 3, "label": 'Node'},
    {"id": 4, "label": 'Node'},
    {"id": 5, "label": 'Node'},
    {"id": 6, "label": 'Node'},
    {"id": 7, "label": 'Node'},
    {"id": 8, "label": 'Node'},
    {"id": 9, "label": 'Node'},
    {"id": 10, "label": 'Node'},
  ],
  "edges": [
    {"id": 1, "base_node": 1, "pair_node": 2},
    {"id": 2, "base_node": 2, "pair_node": 3},
    {"id": 3, "base_node": 2, "pair_node": 4},
    {"id": 4, "base_node": 2, "pair_node": 5},
    {"id": 5, "base_node": 5, "pair_node": 6},
    {"id": 6, "base_node": 5, "pair_node": 7},
    {"id": 7, "base_node": 6, "pair_node": 8},
    {"id": 8, "base_node": 1, "pair_node": 8},
    {"id": 9, "base_node": 4, "pair_node": 6},
    {"id": 10, "base_node": 7, "pair_node": 2},
    {"id": 11, "base_node": 9, "pair_node": 3},
    {"id": 12, "base_node": 10, "pair_node": 9},
    {"id": 13, "base_node": 10, "pair_node": 4},
  ],
};
